# 将来的に対応する規約の読み込み
inherit_from: .rubocop_todo.yml

# 追加した規約ファイル読込
require:
  - rubocop-rails

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# クラスのコメント必須を無視
Documentation:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false

# ネストが深すぎる
BlockNesting:
  Max: 5

# 行が長すぎる
LineLength:
  Enabled: false